name: Votifier
main: com.vexsoftware.votifier.Votifier
version: maven-version-number
description: A plugin that gets notified when votes are made for the server on toplists.
api-version: 1.13
authors: [blakeman8192, Kramer]